### ISSUE TITLE
tengo el problema :5000/audio:1     Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR) recorder.js:67 Oops: Ocurrió un error SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON 

### ISSUE THREAD

**Issue by litocraksito** [ringa-tech/asistente-virtual#10]

**Comment by litocraksito** [comment]
127.0.0.1 - - [15/Aug/2023 19:13:22] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Aug/2023 19:13:22] "GET /static/recorder.css HTTP/1.1" 304 -
127.0.0.1 - - [15/Aug/2023 19:13:22] "GET /static/recorder.js HTTP/1.1" 304 -
127.0.0.1 - - [15/Aug/2023 19:13:22] "GET /static/img/microphone.png HTTP/1.1" 304 -
127.0.0.1 - - [15/Aug/2023 19:13:27] "POST /audio HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\app.py", line 28, in audio
    text = Transcriber().transcribe(audio)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\transcriber.py", line 13, in transcribe
    transcript = openai.Audio.transcribe("whisper-1", audio_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\openai\api_resources\audio.py", line 65, in transcribe
    response, _, api_key = requestor.request("post", url, files=files, params=data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
127.0.0.1 - - [15/Aug/2023 19:13:27] "GET /static/recorder.css HTTP/1.1" 304 -

**Comment by Nelsonrivero** [comment]
hola. lograste solucionarlo ?

**Comment by yandivd** [comment]
Segun veo, no estas accediendo a la api por el error de la cuota excedida: openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details. Necesitas pagar para poder usar la api
