### ISSUE TITLE
Problema cuando instalo los requirements

### ISSUE THREAD

**Issue by flor-k** [ringa-tech/asistente-virtual#13]
Hola! Me da el siguiente error al momento de instalar los requirements. saben por que puede ser?

  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Florencia\AppData\Local\Temp\pip-build-env-_7dy5rze\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Florencia\AppData\Local\Temp\pip-build-env-_7dy5rze\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Florencia\AppData\Local\Temp\pip-build-env-_7dy5rze\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Florencia\AppData\Local\Temp\pip-build-env-_7dy5rze\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Python311\Lib\inspect.py", line 1262, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\inspect.py", line 1244, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\inspect.py", line 1081, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Varano3** [comment]
me ocurre lo mismo, lo has podido solucionar?

**Comment by Jonatandb** [comment]
@flor-k, @Varano3 

Lo acabo de descargar y no tuve problemas al realizar la instalación (Estoy en Windows 10), dejo los pasos que seguí, quizás les faltó crear el entorno virtual (o crearlo les soluciona el problema):

```
Microsoft Windows [Versión 10.0.19045.4291]
(c) Microsoft Corporation. Todos los derechos reservados.

C:\Descargas\asistente-virtual-main>dir
 El volumen de la unidad C es 240 Gb - Windows 10
 El número de serie del volumen es: 3AE2-A490

 Directorio de C:\Descargas\asistente-virtual-main

18/04/2024  13:52    <DIR>          .
18/04/2024  13:52    <DIR>          ..
09/07/2023  03:27                53 .env.example
09/07/2023  03:27             3.245 .gitignore
09/07/2023  03:27             2.616 app.py
09/07/2023  03:27             4.735 llm.py
09/07/2023  03:27               433 pc_command.py
09/07/2023  03:27             1.636 README.md
09/07/2023  03:27               858 requirements.txt
09/07/2023  03:27    <DIR>          static
09/07/2023  03:27    <DIR>          templates
09/07/2023  03:27               447 transcriber.py
09/07/2023  03:27             1.308 tts.py
09/07/2023  03:27               836 weather.py
              10 archivos         16.167 bytes
               4 dirs  19.227.889.664 bytes libres

C:\Descargas\asistente-virtual-main>py -m venv .venv

C:\Descargas\asistente-virtual-main>.\.venv\Scripts\activate

(.venv) C:\Descargas\asistente-virtual-main>pip install -r requirements.txt
Collecting aiohttp==3.8.4
  Using cached aiohttp-3.8.4-cp311-cp311-win_amd64.whl (317 kB)
Collecting aiosignal==1.3.1
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attrs==23.1.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting blinker==1.6.2
  Using cached blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting certifi==2023.5.7
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting charset-normalizer==3.1.0
  Using cached charset_normalizer-3.1.0-cp311-cp311-win_amd64.whl (96 kB)
Collecting click==8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting colorama==0.4.6
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting Flask==2.3.2
  Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
Collecting frozenlist==1.3.3
  Using cached frozenlist-1.3.3-cp311-cp311-win_amd64.whl (32 kB)
Collecting gTTS==2.3.2
  Using cached gTTS-2.3.2-py3-none-any.whl (28 kB)
Collecting idna==3.4
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting itsdangerous==2.1.2
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting Jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe==2.1.3
  Using cached MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl (17 kB)
Collecting multidict==6.0.4
  Using cached multidict-6.0.4-cp311-cp311-win_amd64.whl (28 kB)
Collecting openai==0.27.8
  Using cached openai-0.27.8-py3-none-any.whl (73 kB)
Collecting playsound==1.3.0
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Preparing metadata (setup.py) ... done
Collecting python-dotenv==1.0.0
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting requests==2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting tqdm==4.65.0
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting urllib3==2.0.3
  Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
Collecting Werkzeug==2.3.6
  Using cached Werkzeug-2.3.6-py3-none-any.whl (242 kB)
Collecting yarl==1.9.2
  Using cached yarl-1.9.2-cp311-cp311-win_amd64.whl (60 kB)
Installing collected packages: playsound, urllib3, python-dotenv, multidict, MarkupSafe, itsdangerous, idna, frozenlist, colorama, charset-normalizer, certifi, blinker, attrs, async-timeout, yarl, Werkzeug, tqdm, requests, Jinja2, click, aiosignal, gTTS, Flask, aiohttp, openai
  DEPRECATION: playsound is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for playsound ... done
Successfully installed Flask-2.3.2 Jinja2-3.1.2 MarkupSafe-2.1.3 Werkzeug-2.3.6 aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-23.1.0 blinker-1.6.2 certifi-2023.5.7 charset-normalizer-3.1.0 click-8.1.3 colorama-0.4.6 frozenlist-1.3.3 gTTS-2.3.2 idna-3.4 itsdangerous-2.1.2 multidict-6.0.4 openai-0.27.8 playsound-1.3.0 python-dotenv-1.0.0 requests-2.31.0 tqdm-4.65.0 urllib3-2.0.3 yarl-1.9.2

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

(.venv) C:\Descargas\asistente-virtual-main>pip list
Package            Version
------------------ --------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              23.1.0
blinker            1.6.2
certifi            2023.5.7
charset-normalizer 3.1.0
click              8.1.3
colorama           0.4.6
Flask              2.3.2
frozenlist         1.3.3
gTTS               2.3.2
idna               3.4
itsdangerous       2.1.2
Jinja2             3.1.2
MarkupSafe         2.1.3
multidict          6.0.4
openai             0.27.8
pip                22.3.1
playsound          1.3.0
python-dotenv      1.0.0
requests           2.31.0
setuptools         65.5.0
tqdm               4.65.0
urllib3            2.0.3
Werkzeug           2.3.6
yarl               1.9.2

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

(.venv) C:\Descargas\asistente-virtual-main>
```
