### ISSUE TITLE
tengo este problema

### ISSUE THREAD

**Issue by yeickoff** [ringa-tech/asistente-virtual#4]
(env) PS C:\Users\yeickoff\Desktop\asistente-virtual-main> flask --app app run --debug
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 997-924-310
127.0.0.1 - - [12/Jul/2023 01:36:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Jul/2023 01:36:53] "GET /static/recorder.css HTTP/1.1" 200 -
127.0.0.1 - - [12/Jul/2023 01:36:53] "GET /static/recorder.js HTTP/1.1" 200 -
127.0.0.1 - - [12/Jul/2023 01:36:53] "GET /static/img/microphone.png HTTP/1.1" 200 -
127.0.0.1 - - [12/Jul/2023 01:36:54] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [12/Jul/2023 01:37:00] "POST /audio HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 
2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 
2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 
2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 
1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 
1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\flask\app.py", line 
1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\app.py", line 27, in audio
    text = Transcriber().transcribe(audio)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\transcriber.py", line 13, in transcribe   
    transcript = openai.Audio.transcribe("whisper-1", audio_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\openai\api_resources\audio.py", line 55, in transcribe
    requestor, files, data = cls._prepare_request(
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\openai\api_resources\audio.py", line 28, in _prepare_request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\openai\api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yeickoff\Desktop\asistente-virtual-main\env\Lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
127.0.0.1 - - [12/Jul/2023 01:37:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Jul/2023 01:37:19] "GET /static/recorder.css HTTP/1.1" 304 -
127.0.0.1 - - [12/Jul/2023 01:37:19] "GET /static/recorder.js HTTP/1.1" 304 -
127.0.0.1 - - [12/Jul/2023 01:37:19] "GET /static/img/microphone.png HTTP/1.1" 304 -

**Comment by yeickoff** [comment]
ayuda

**Comment by ringa-tech** [comment]
Hola, la parte relevante del error es la siguiente:
_openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key_

Este proyecto está hecho para funcionar con llaves de servicios en la nube: Whisper para pasar voz a texto, OpenAI / GPT para procesar el texto, e ElevenLabs para pasar texto a voz.

Para poder saber qué llaves tomar, revisa el archivo README, recomiendo todo pero para esto, específicamente la parte de agregar un archivo ".env". También puedes copiar el archivo .env.example en un nuevo archivo .env y poner las llaves necesarias.

Si yo o alguien le agrega opciones de código abierto que no requieran dicha llaves, se actualizará este repositorio.
