### ISSUE TITLE
Error al reproducir el audio

### ISSUE THREAD

**Issue by Alfredogc21** [ringa-tech/asistente-virtual#8]
Amigo resulta que al momento generar una respuesta, el audio response.mp3 no funciona, al parecer no reproduce lo generado debido a que el archivo mencionado solo tiene 1kb ósea no tiene información

**Comment by Emilien203** [comment]
A mi en la consola de la web me sale el siguiente error:

```
recorfer.js:52  Tenemos blobios!
recorder.js:59     POST http://localhost:5000/audio 500 (INTERNAL SERVER ERROR)
doPreview @ recorder.js:59
recorder.js:67 Oops: Ocurrió un error SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
```

Y luego en la terminal de vs code  me sale al final: 
`FileNotFoundError: [Errno 2] No such file or directory: 'static/response.mp3'`

pero aqui dejo todo lo demas:

```
127.0.0.1 - - [19/Jul/2023 23:58:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2023 23:58:30] "GET /static/recorder.css HTTP/1.1" 304 -
127.0.0.1 - - [19/Jul/2023 23:58:30] "GET /static/recorder.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Jul/2023 23:58:30] "GET /static/img/microphone.png HTTP/1.1" 304 -
127.0.0.1 - - [19/Jul/2023 23:58:37] "POST /audio HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "a:\asistente-virtual-main\.env\Lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "a:\asistente-virtual-main\.env\Lib\site-packages\werkzeug\serving.py", line 325, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "a:\asistente-virtual-main\.env\app.py", line 62, in audio
    tts_file = TTS().process(final_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "a:\asistente-virtual-main\.env\tts.py", line 36, in process
    with open("static/" + file_name, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'static/response.mp3'
```

**Comment by wuilmerbolivar** [comment]
> 127.0.0.1 - - [19/Jul/2023 23:58:30] "GET / HTTP/1.1" 200 -
> 127.0.0.1 - - [19/Jul/2023 23:58:30] "GET /static/recorder.css HTTP/1.1" 304 -
> 127.0.0.1 - - [19/Jul/2023 23:58:30] "GET /static/recorder.js HTTP/1.1" 304 -
> 127.0.0.1 - - [19/Jul/2023 23:58:30] "GET /static/img/microphone.png HTTP/1.1" 304 -
> 127.0.0.1 - - [19/Jul/2023 23:58:37] "POST /audio HTTP/1.1" 500 -
> Error on request:
> Traceback (most recent call last):
>   File "a:\asistente-virtual-main\.env\Lib\site-packages\werkzeug\serving.py", line 364, in run_wsgi
>     execute(self.server.app)
>   File "a:\asistente-virtual-main\.env\Lib\site-packages\werkzeug\serving.py", line 325, in execute
>     application_iter = app(environ, start_response)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 2213, in __call__
>     return self.wsgi_app(environ, start_response)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
>     response = self.handle_exception(e)
>                ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
>     response = self.full_dispatch_request()
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
>     rv = self.dispatch_request()
>          ^^^^^^^^^^^^^^^^^^^^^^^
>   File "a:\asistente-virtual-main\.env\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "a:\asistente-virtual-main\.env\app.py", line 62, in audio
>     tts_file = TTS().process(final_response)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "a:\asistente-virtual-main\.env\tts.py", line 36, in process
>     with open("static/" + file_name, 'wb') as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'static/response.mp3'

Revisa la función process en el archivo 'tts.py' en la línea 36 para asegurarte de que no haya errores en la generación del archivo 'response.mp3' y que la ruta del archivo se esté manejando correctamente. El error te dice: FileNotFoundError, lo que indica que no encuntra el archivo en la ruta: 'static/response.mp3' entonces no esta generando archivo, chequea los permisos del navegador en ese directorio.

**Comment by WilliamsWick** [comment]
Amigo resulta que al momento generar una respuesta, el audio response.mp3 me muestra lo siguiente: 
![image](https://github.com/ringa-tech/asistente-virtual/assets/80177649/632a11bf-0202-4048-9090-43649ea3acdc) y no lo que grabe en la pag.
