### ISSUE TITLE
Algunos problemas solucionados

### ISSUE THREAD

**Issue by wuilmerbolivar** [ringa-tech/asistente-virtual#9]
Quiero compartir cómo resolví algunos problemas que surgieron durante la instalación y prueba. Primero, es importante mencionar que las versiones gratuitas de las APIs pueden tener ciertas limitaciones, así que si es posible, es recomendable optar por una versión de pago.

Mi primer obstáculo fue que use un linux virtualizado, pero quería poder ejecutarlo en cualquier computadora de mi red local, permitiéndome usar dispositivos conectados a esos equipos sin problemas. Para lograr esto, utilicé el siguiente comando:

`flask run --host=0.0.0.0 --port=5000 --debug`

Gracias a esto, logré acceder a la aplicación desde cualquier dispositivo en mi red local, no solo desde el equipo en el que la estaba ejecutando inicialmente.

Sin embargo, esta solución trajo otro problema: el error ERR_SSL_PROTOCOL_ERROR. El acceso al micrófono requería una conexión segura (HTTPS), pero como mi servidor Apache local no tenía un certificado válido, decidí crear uno autofirmado utilizando el siguiente comando:

`openssl req -x509 -newkey rsa:4096 -nodes -out certificado.crt -keyout llave_privada.key -days 365`

Generé el certificado y la llave en el mismo directorio donde cloné mi aplicación. Después, me encontré con el siguiente mensaje en la consola: 'WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.'

Ante esta advertencia, opté por instalar Gunicorn con un simple comando:

`pip install gunicorn`

Gunicorn me permitió ejecutar la aplicación de la siguiente manera:

`gunicorn app:app --bind 0.0.0.0:5000`

Para utilizar el certificado que había creado, primero lo exporté al navegador y luego lo indiqué en la configuración de la aplicación:

`gunicorn app:app --bind 0.0.0.0:5000 --certfile certificado.crt --keyfile llave_privada.key`

Finalmente, pude acceder al micrófono, utilizar la aplicación, guardar los archivos, transcribirlos y trabajar con ellos sin problemas. Sin embargo, es importante tener en cuenta las restricciones de uso de la API gratuita.

Espero que esta descripción de cómo solucioné estos problemas sea útil para otros usuarios que puedan enfrentar situaciones similares.

**Comment by YakelinEdith** [comment]
**Disculpa, ¿Que versión de Python usaste? ya que al ejecutar gunicorn me da una serie de errores, yo tengo Python 3.11.4**

> Traceback (most recent call last):
> File "<frozen runpy>", line 198, in _run_module_as_main
> File "<frozen runpy>", line 88, in _run_code
> File "C:\Users\Yakelin\Desktop\asistente-virtual-f015e71a98a6424b19e7bbc4b3a036bbec5b69ba\env\Scripts\gunicorn.exe\__main__.py", line 4, in <module>
> File "C:\Users\Yakelin\Desktop\asistente-virtual-f015e71a98a6424b19e7bbc4b3a036bbec5b69ba\env\Lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
> from gunicorn.app.base import Application
> File "C:\Users\Yakelin\Desktop\asistente-virtual-f015e71a98a6424b19e7bbc4b3a036bbec5b69ba\env\Lib\site-packages\gunicorn\app\base.py", line 11, in <module>
> from gunicorn import util
> File "C:\Users\Yakelin\Desktop\asistente-virtual-f015e71a98a6424b19e7bbc4b3a036bbec5b69ba\env\Lib\site-packages\gunicorn\util.py", line 8, in <module>
> import fcntl
> ModuleNotFoundError: No module named 'fcntl

'
